version: 2.1
job:
  build:
    docker: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Build
          command: yarn build
